# Generated by Django 4.2.11 on 2024-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=255)),
                ('risposta', models.BooleanField()),
                ('descrizione', models.TextField()),
            ],
        ),
    ]
