# Generated by Django 4.2.11 on 2024-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_domanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
